version: '3.3'

volumes:
    postgres_data: {}

services:

  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    command: /start.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: .env

  locust:
    build:
      context: ./test
    ports:
      - 8089:8089
    depends_on:
      - backend
    volumes:
      - ./test:/app_test
    command: locust --host=http://localhost:8000
    restart: on-failure
    env_file: .env

  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./.env:/app/.env:ro
      - ./frontend:/app
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    working_dir: /app
    restart: on-failure

  postgres:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: none
